// All trip content lives here. Edit anything below and the site updates.
// Each event has a unique `slug` used for its detail page URL: /event/<slug>

export const TRIP = {
  title: "Chicago 2026",
  subtitle: "Family Visit · July 12–17",
  intro:
    "Everything we have planned, plus ideas and places to eat — all in one spot. Tap any item for details, maps, and links.",
};

export const events = {
  "tiny-tapp": {
    slug: "tiny-tapp",
    title: "Drinks, Dinner & Live Music",
    venue: "Tiny Tapp & Café",
    time: "Evening",
    category: "Food & Drinks",
    emoji: "🎶",
    short: "Welcome dinner on the Riverwalk with live music as everyone arrives.",
    long: "A relaxed waterfront spot right on the Chicago Riverwalk — the perfect low-key welcome as everyone trickles into town. Think cocktails, casual American food, and a summer-party feel right on the river. Bonus: live music plays on Sundays from 5–7 PM, so timing dinner around then is a nice touch.",
    address: "55 W Riverwalk S, Chicago, IL 60601",
    mapQuery: "Tiny Tapp & Cafe Chicago Riverwalk",
    website: "https://www.tinytapp.com/",
    tips: [
      "Live music Sundays 5–7 PM — great to aim for since everyone arrives Sunday.",
      "It's on the lower Riverwalk level — take the stairs down near Wabash or State.",
      "Walk-in friendly, but the patio fills up on warm evenings.",
    ],
    price: "$$ · casual",
  },

  "pancake-house": {
    slug: "pancake-house",
    title: "Breakfast at The Original Pancake House",
    venue: "The Original Pancake House · Gold Coast",
    time: "Morning",
    category: "Breakfast",
    emoji: "🥞",
    short: "Classic Gold Coast breakfast institution.",
    long: "A longtime Chicago favorite tucked into the Gold Coast, famous for its baked apple pancake and fluffy classics. Cozy, reliable, and a great way to start the big sightseeing day before heading down to The Bean.",
    address: "22 E Bellevue Pl, Chicago, IL 60611",
    mapQuery: "Original Pancake House 22 E Bellevue Pl Chicago",
    website: "https://www.theinfatuation.com/chicago/reviews/the-original-pancake-house",
    tips: [
      "Order the signature baked apple pancake — it's the one to get.",
      "Go a little early on weekends to beat the wait.",
      "It's in the Gold Coast, about a 10-minute ride south to Millennium Park and The Bean.",
    ],
    price: "$$ · breakfast",
  },

  "the-bean": {
    slug: "the-bean",
    title: "The Bean & Millennium Park",
    venue: "Cloud Gate, Millennium Park",
    time: "Late morning",
    category: "Sightseeing",
    emoji: "🫘",
    short: "Chicago's iconic mirrored sculpture and the gardens around it.",
    long: "Cloud Gate — 'The Bean' — is the must-do photo stop. The surrounding Millennium Park is flat, paved, and easy to stroll, with the Lurie Garden, the Pritzker Pavilion, and Crown Fountain all nearby. A great, low-effort way to soak in downtown.",
    address: "201 E Randolph St, Chicago, IL 60602",
    mapQuery: "Cloud Gate The Bean Millennium Park Chicago",
    website: "https://www.chicago.gov/city/en/depts/dca/supp_info/millennium_park_-_artarchitecture.html",
    tips: [
      "Completely free and flat — easy walking with plenty of benches.",
      "Cross the BP Bridge into Maggie Daley Park for shade and gardens.",
      "Mornings are less crowded for photos.",
    ],
    price: "Free",
  },

  "downtown-walk": {
    slug: "downtown-walk",
    title: "Stroll Downtown",
    venue: "The Loop & Riverwalk",
    time: "Midday",
    category: "Sightseeing",
    emoji: "🚶",
    short: "An easy wander through the Loop and along the river.",
    long: "Wander from Millennium Park toward the Chicago Riverwalk and Michigan Avenue. The Riverwalk is flat and scenic, with plenty of places to sit, grab a drink, or watch the boats. Keep it as long or short as energy allows — there are benches and cafés all along the way.",
    address: "Chicago Riverwalk, Chicago, IL",
    mapQuery: "Chicago Riverwalk",
    website: "https://www.chicago.gov/city/en/sites/chicagoriverwalk/home.html",
    tips: [
      "The Riverwalk is flat with frequent benches and shade — easy on the legs.",
      "Plenty of cafés and washrooms along the way for breaks.",
    ],
    price: "Free",
  },

  "lunch-monday": {
    slug: "lunch-monday",
    title: "Lunch Downtown",
    venue: "Your pick near the river",
    time: "Afternoon",
    category: "Lunch",
    emoji: "🍽️",
    short: "Grab a bite before the afternoon boat cruise.",
    long: "Keep lunch flexible and close to the river so you're set for the 4:30 PM cruise from Navy Pier. A few easy, group-friendly options nearby are listed on the Dinner & Dining page — many also do lunch.",
    address: "Near the Chicago Riverwalk",
    mapQuery: "restaurants Chicago Riverwalk",
    website: null,
    tips: [
      "Stay near the river so you can get to Navy Pier in time for the 4:30 cruise.",
      "Cabs and rideshares to Navy Pier take about 10–15 minutes from the Loop.",
    ],
    price: "$$",
  },

  "boat-cruise": {
    slug: "boat-cruise",
    title: "Architecture Boat Cruise",
    venue: "Shoreline Sightseeing · Navy Pier",
    time: "4:30 PM · 90 minutes",
    category: "Sightseeing",
    emoji: "⛵",
    short: "90-minute river cruise past 40+ landmark buildings.",
    long: "Hands-down one of the best things to do in Chicago, and ideal for this group — you're seated the whole time while a guide narrates the city's incredible architecture from the water. The 90-minute tour departs from Navy Pier and glides along the river past more than 40 iconic buildings.",
    address: "Navy Pier, 600 E Grand Ave, Chicago, IL 60611",
    mapQuery: "Shoreline Sightseeing Navy Pier Chicago",
    website: "https://shorelinesightseeing.com/tours/architecture-river-tour/",
    ticket: "https://shorelinesightseeing.com/tours/architecture-river-tour/",
    tips: [
      "Book ahead and confirm the 4:30 PM, 90-minute departure from Navy Pier (not the Michigan Ave dock).",
      "Adult tickets start around $46; arrive 30 minutes early to board.",
      "Bring a light layer — it's breezier out on the water.",
      "Seated the entire time — comfortable for everyone.",
    ],
    price: "$$ · ~$46/adult",
  },

  "group-dinner-mon": {
    slug: "group-dinner-mon",
    title: "Group Dinner",
    venue: "See Dinner & Dining ideas",
    time: "Evening",
    category: "Food & Drinks",
    emoji: "🍷",
    short: "Big group dinner — picks on the Dining page.",
    long: "A relaxed dinner for the whole crew. Check the Dinner & Dining page for affordable spots that can seat 6–7 on shorter notice — Quartino and Café Ba Ba Reeba are especially easy with a group.",
    address: "Chicago, IL",
    mapQuery: "group dinner restaurants Chicago",
    website: null,
    tips: ["See the Dinner & Dining page for group-friendly picks and how to reserve."],
    price: "$$",
  },

  "obama-center": {
    slug: "obama-center",
    title: "Obama Presidential Center",
    venue: "Jackson Park",
    time: "Daytime",
    category: "Museum",
    emoji: "🏛️",
    short: "The brand-new presidential center and library, opened June 2026.",
    long: "Newly opened in June 2026 on a 20-acre campus in Jackson Park near Lake Michigan. The grounds, gardens, and public spaces are free to walk; the museum itself requires a timed ticket. A meaningful, mostly indoor experience with plenty of places to sit.",
    address: "Jackson Park, S Stony Island Ave, Chicago, IL 60637",
    mapQuery: "Obama Presidential Center Jackson Park Chicago",
    website: "https://www.obama.org/visit/",
    ticket: "https://www.obama.org/visit/",
    tips: [
      "Museum tickets are timed and sell out well in advance — book as early as you can.",
      "The campus grounds and gardens are free even without a museum ticket.",
      "About a 20–25 minute drive south of downtown.",
    ],
    price: "Grounds free · museum ticketed",
  },

  "group-dinner-tue": {
    slug: "group-dinner-tue",
    title: "Group Dinner",
    venue: "See Dinner & Dining ideas",
    time: "Evening",
    category: "Food & Drinks",
    emoji: "🍷",
    short: "Big group dinner — picks on the Dining page.",
    long: "Another whole-group dinner. The Dinner & Dining page has affordable options that handle groups well — consider somewhere on the South Side or in the Loop if you're coming back from the Obama Center.",
    address: "Chicago, IL",
    mapQuery: "group dinner restaurants Chicago",
    website: null,
    tips: ["See the Dinner & Dining page for group-friendly picks."],
    price: "$$",
  },

  "brunchery-breakfast": {
    slug: "brunchery-breakfast",
    title: "Breakfast at The Brunchery",
    venue: "The Brunchery",
    time: "Morning",
    category: "Breakfast",
    emoji: "🍳",
    short: "Cozy Lincoln Park brunch spot serving since 1938.",
    long: "A neighborhood brunch favorite in Lincoln Park with house-made syrups, french toast flights, benedicts, and big pancakes. Walk-ins only and a warm, unfussy vibe — a nice slow start before the spa.",
    address: "2552 N Clark St, Chicago, IL 60614",
    mapQuery: "The Brunchery 2552 N Clark St Chicago",
    website: "https://brunchonclark.com/",
    tips: [
      "Walk-ins only (no reservations) — go a little early to beat the wait.",
      "Open daily 9 AM–3 PM.",
    ],
    price: "$$ · brunch",
  },

  "spa-day": {
    slug: "spa-day",
    title: "Spa & Massage at Healthy Zu Spa",
    venue: "Healthy Zu Spa · West Loop",
    time: "Afternoon",
    category: "Relax",
    emoji: "💆",
    short: "Affordable Chinese massage and reflexology in the West Loop.",
    long: "A well-earned midweek reset. Healthy Zu Spa is a well-reviewed, wallet-friendly spot in the West Loop known for Chinese reflexology foot massage and body work. Call ahead to book everyone around the same time so the group can go together.",
    address: "120 N Halsted St, Chicago, IL 60661",
    mapQuery: "Healthy Zu Spa 120 N Halsted St Chicago",
    website: "https://www.healthyzu-spa.com/",
    tips: [
      "Appointments are preferred — call ahead to book the group at the same time. Walk-ins accepted when there's room.",
      "Open Mon–Sat 10 AM–9:30 PM, Sun 10:30 AM–9 PM.",
      "Known for reflexology foot massage — a relaxing, lower-key option.",
    ],
    price: "$ · affordable",
  },

  "dinner-wed": {
    slug: "dinner-wed",
    title: "Dinner",
    venue: "See Dinner & Dining ideas",
    time: "Evening",
    category: "Food & Drinks",
    emoji: "🍽️",
    short: "Dinner out — picks on the Dining page.",
    long: "An easy dinner to wrap up the spa day. See the Dinner & Dining page for relaxed, affordable spots that seat a group.",
    address: "Chicago, IL",
    mapQuery: "group dinner restaurants Chicago",
    website: null,
    tips: ["See the Dinner & Dining page for group-friendly picks."],
    price: "$$",
  },

  "biking-lakefront": {
    slug: "biking-lakefront",
    title: "Biking the Lakefront Trail",
    venue: "Lakefront Trail",
    time: "Morning",
    category: "Outdoors",
    emoji: "🚲",
    short: "Flat, scenic ride along Lake Michigan.",
    long: "The Lakefront Trail runs ~18 flat, paved miles along Lake Michigan with stunning skyline views. You don't have to do all of it — rent bikes near Navy Pier or Millennium Park and ride as far as feels good, then turn back. Easy, breezy, and gorgeous.",
    address: "Lakefront Trail, Chicago, IL",
    mapQuery: "Chicago Lakefront Trail bike rental Navy Pier",
    website: "https://www.bobbysbikehike.com/",
    tips: [
      "Bobby's Bike Hike (near Navy Pier) and Divvy bike-share both rent by the hour.",
      "The trail is flat and paved — pick a turnaround point and ride at your own pace.",
      "Ride in the morning before it gets hot; bring water and sunscreen.",
    ],
    price: "$ · bike rental",
  },

  "roller-skating": {
    slug: "roller-skating",
    title: "Summer Skate at Navy Pier",
    venue: "Navy Pier · Crystal Gardens",
    time: "Afternoon (opt.)",
    category: "Fun",
    emoji: "🛼",
    short: "Retro indoor roller rink, new for summer 2026.",
    long: "A fun, optional add-on after biking. Navy Pier's new lakefront roller rink lives inside the old Crystal Gardens atrium with a '90s retro vibe. Indoor, air-conditioned, and easygoing — skate or just enjoy the scene.",
    address: "Navy Pier, 600 E Grand Ave, Chicago, IL 60611",
    mapQuery: "Summer Skate Navy Pier Crystal Gardens",
    website: "https://navypier.org/pier-events/summerskate/",
    ticket: "https://navypier.org/pier-events/summerskate/",
    tips: [
      "Thursday hours are noon–8 PM; tickets start around $17.50.",
      "Indoor and air-conditioned — a nice break from the heat.",
      "Totally optional — easy to skip if everyone's tired from biking.",
    ],
    price: "$ · ~$17.50",
  },

  "ann-sather": {
    slug: "ann-sather",
    title: "Breakfast at Ann Sather",
    venue: "Ann Sather",
    time: "Morning",
    category: "Breakfast",
    emoji: "🍯",
    short: "Beloved Swedish diner famous for cinnamon rolls.",
    long: "A Chicago institution since 1945, known for gooey cinnamon rolls and hearty Swedish-American breakfasts at fair prices. The nearest locations are in Lakeview (Belmont and Broadway), a short ride north of the Gold Coast / Oak Street Beach area.",
    address: "909 W Belmont Ave, Chicago, IL 60657 (Lakeview)",
    mapQuery: "Ann Sather 909 W Belmont Ave Chicago",
    website: "http://annsather.com/",
    tips: [
      "Order the cinnamon rolls — they're the signature.",
      "Open daily 7 AM–3 PM; a quick ride from Oak Street Beach.",
    ],
    price: "$$ · breakfast",
  },

  "oak-street-beach": {
    slug: "oak-street-beach",
    title: "Oak Street Beach",
    venue: "Gold Coast lakefront",
    time: "Daytime",
    category: "Outdoors",
    emoji: "🏖️",
    short: "City beach with skyline views at the edge of the Gold Coast.",
    long: "A relaxing send-off spot — a sandy beach right where the Gold Coast meets the lake, with the skyline rising behind you. Easy to reach, with a flat lakefront path, a beachfront café, and plenty of room to sit and unwind.",
    address: "1000 N Lake Shore Dr, Chicago, IL 60611",
    mapQuery: "Oak Street Beach Chicago",
    website: "https://www.chicagoparkdistrict.com/parks-facilities/oak-street-beach",
    tips: [
      "Flat, paved path access — no stairs needed from the Gold Coast side.",
      "Oak Street Beachstro café is right there for drinks and a bite.",
      "Great final-morning stop before heading out.",
    ],
    price: "Free",
  },
};

// Day-by-day plan. `group` notes who's around.
export const days = [
  {
    date: "2026-07-12",
    weekday: "Sunday",
    label: "Jul 12",
    title: "Everyone Arrives",
    group: "Whole Group",
    note: "Travel day — keep it easy. Live music at Tiny Tapp runs 5–7 PM.",
    eventSlugs: ["tiny-tapp"],
  },
  {
    date: "2026-07-13",
    weekday: "Monday",
    label: "Jul 13",
    title: "Downtown & The River",
    group: "Whole Group",
    note: "The big sightseeing day, ending with the 4:30 PM boat cruise.",
    eventSlugs: [
      "pancake-house",
      "the-bean",
      "downtown-walk",
      "lunch-monday",
      "boat-cruise",
      "group-dinner-mon",
    ],
  },
  {
    date: "2026-07-14",
    weekday: "Tuesday",
    label: "Jul 14",
    title: "Obama Presidential Center",
    group: "Whole Group",
    note: "Book museum tickets in advance — they're timed entry.",
    eventSlugs: ["obama-center", "group-dinner-tue"],
  },
  {
    date: "2026-07-15",
    weekday: "Wednesday",
    label: "Jul 15",
    title: "Brunch & Spa Day",
    group: "Whole Group",
    note: "Last full day everyone's together.",
    eventSlugs: ["brunchery-breakfast", "spa-day", "dinner-wed"],
  },
  {
    date: "2026-07-16",
    weekday: "Thursday",
    label: "Jul 16",
    title: "Lakefront & Navy Pier",
    group: "Mom, Taylor, Bro T",
    note: "No Chicago home baseball game today — but the Cubs are home Friday (see Ideas).",
    eventSlugs: ["biking-lakefront", "roller-skating"],
  },
  {
    date: "2026-07-17",
    weekday: "Friday",
    label: "Jul 17",
    title: "Breakfast & The Beach",
    group: "Mom, Taylor, Bro T",
    note: "Relaxed final morning before goodbyes.",
    eventSlugs: ["ann-sather", "oak-street-beach"],
  },
];

// Extra ideas for first-time visitors. Chosen for low-walking, lots of seating, mostly indoor or flat.
export const ideas = [
  {
    title: "Art Institute of Chicago",
    emoji: "🖼️",
    blurb:
      "World-class museum with the famous Impressionist galleries. Indoor, benches throughout, and you can do as much or as little as you like.",
    why: "Indoor · plenty of seating",
    website: "https://www.artic.edu/",
    mapQuery: "Art Institute of Chicago",
  },
  {
    title: "Chicago Cultural Center",
    emoji: "💠",
    blurb:
      "Free landmark building with the world's largest Tiffany stained-glass dome. Beautiful, quick, and easy — right across from Millennium Park.",
    why: "Free · indoor · short visit",
    website: "https://www.chicago.gov/city/en/depts/dca/supp_info/chicago_culturalcenter.html",
    mapQuery: "Chicago Cultural Center",
  },
  {
    title: "Skyline view: 360 Chicago or Skydeck",
    emoji: "🌆",
    blurb:
      "For a high-up view: 360 Chicago (875 N Michigan) and Skydeck (Willis Tower) are both elevator-up, paid observation decks. For a free version, the rooftop bars at LondonHouse or Cindy's give you the view with a drink — no ticket needed.",
    why: "Elevator access · sit-down options",
    website: "https://360chicago.com/",
    mapQuery: "360 Chicago observation deck",
  },
  {
    title: "Garfield Park Conservatory",
    emoji: "🌿",
    blurb:
      "One of the largest indoor gardens in the country and completely free. Flat, glass-roofed rooms full of plants — calm and easy walking.",
    why: "Free · flat · indoor",
    website: "https://garfieldconservatory.org/",
    mapQuery: "Garfield Park Conservatory Chicago",
  },
  {
    title: "Hop-On Hop-Off Trolley / Bus Tour",
    emoji: "🚌",
    blurb:
      "See the whole city while seated. Hop off at the stops you like and back on when you're ready — ideal when long walks aren't the goal.",
    why: "Seated · see everything",
    website: "https://www.choosechicago.com/things-to-do/tours/",
    mapQuery: "Chicago hop on hop off bus tour",
  },
  {
    title: "Lincoln Park Zoo & Conservatory",
    emoji: "🦁",
    blurb:
      "Free, flat, and shaded zoo right in the city, with a small conservatory next door. Easy loops and lots of benches.",
    why: "Free · flat · benches",
    website: "https://www.lpzoo.org/",
    mapQuery: "Lincoln Park Zoo Chicago",
  },
  {
    title: "Cubs Game at Wrigley Field (Fri, Jul 17)",
    emoji: "⚾",
    blurb:
      "There's no Chicago home game Thursday, but the Cubs host the Twins at Wrigley starting Friday Jul 17 — a fun, affordable option for the smaller group. Upper-deck seats are easy on the wallet.",
    why: "Affordable · seated · iconic",
    website: "https://www.mlb.com/cubs/schedule",
    mapQuery: "Wrigley Field Chicago",
  },
  {
    title: "Maggie Daley Park & The Riverwalk",
    emoji: "🌳",
    blurb:
      "Two free, flat, beautiful strolls steps from The Bean — gardens, art, and river views with plenty of places to rest.",
    why: "Free · flat · scenic",
    website: "https://maggiedaleypark.com/",
    mapQuery: "Maggie Daley Park Chicago",
  },
  {
    title: "Deep-Dish Pizza, the Chicago Classic",
    emoji: "🍕",
    blurb:
      "You can't visit without trying it. Lou Malnati's, Pequod's, and Giordano's are the go-tos. Casual, group-friendly, and very Chicago.",
    why: "Casual · iconic",
    website: "https://www.loumalnatis.com/",
    mapQuery: "Lou Malnati's Pizzeria Chicago",
  },
];

// Affordable, group-friendly dinner spots that can usually handle 6–7 on shorter notice.
export const dining = [
  {
    title: "Quartino Ristorante",
    area: "River North",
    cuisine: "Italian · small plates",
    emoji: "🍝",
    blurb:
      "Shareable Italian small plates at prices that are tough to beat downtown, and genuinely great with groups. A top pick for the big-group nights.",
    price: "$$",
    website: "https://www.quartinochicago.com/",
    mapQuery: "Quartino Ristorante Chicago",
  },
  {
    title: "Café Ba-Ba-Reeba!",
    area: "Lincoln Park",
    cuisine: "Spanish tapas",
    emoji: "🥘",
    blurb:
      "Tapas and sangria made for sharing — lively, affordable, and used to seating groups. Easy and fun for a crowd.",
    price: "$$",
    website: "https://www.cafebabareeba.com/",
    mapQuery: "Cafe Ba Ba Reeba Chicago",
  },
  {
    title: "Portillo's",
    area: "River North",
    cuisine: "Chicago classics",
    emoji: "🌭",
    blurb:
      "Italian beef, Chicago dogs, and chocolate cake. Counter-order, no reservations, and big enough to seat any group instantly. The most reliable short-notice option.",
    price: "$",
    website: "https://www.portillos.com/",
    mapQuery: "Portillo's River North Chicago",
  },
  {
    title: "Lou Malnati's Pizzeria",
    area: "Multiple (River North)",
    cuisine: "Deep-dish pizza",
    emoji: "🍕",
    blurb:
      "The classic Chicago deep-dish. A couple of pies feed a group cheaply, and larger tables are usually doable on shorter notice.",
    price: "$$",
    website: "https://www.loumalnatis.com/",
    mapQuery: "Lou Malnati's River North Chicago",
  },
  {
    title: "The Purple Pig",
    area: "Magnificent Mile",
    cuisine: "Mediterranean · small plates",
    emoji: "🐷",
    blurb:
      "Beloved shared-plates spot right on Michigan Ave. Slightly busier, so call ahead for 6–7, but a fantastic group meal.",
    price: "$$",
    website: "https://thepurplepigchicago.com/",
    mapQuery: "The Purple Pig Chicago",
  },
  {
    title: "Beatrix",
    area: "River North / Loop",
    cuisine: "American · healthy-ish",
    emoji: "🥗",
    blurb:
      "Crowd-pleasing menu with something for everyone, roomy tables, and several locations. Reliable and group-friendly.",
    price: "$$",
    website: "https://www.beatrixrestaurants.com/",
    mapQuery: "Beatrix restaurant Chicago",
  },
  {
    title: "The Dearborn",
    area: "The Loop",
    cuisine: "American tavern",
    emoji: "🍔",
    blurb:
      "Polished but unfussy American food right in the Loop, with room for groups and a wide-ranging menu. Central and dependable.",
    price: "$$",
    website: "https://thedearborntavern.com/",
    mapQuery: "The Dearborn restaurant Chicago Loop",
  },
  {
    title: "Bar Siena",
    area: "West Loop",
    cuisine: "Italian · pizza & small plates",
    emoji: "🍕",
    blurb:
      "A big, lively two-story spot on West Loop's restaurant row. Shareable Italian street food, easy for a group, and open late.",
    price: "$$",
    website: "https://www.barsiena.com/",
    mapQuery: "Bar Siena 832 W Randolph St Chicago",
  },
  {
    title: "Greek Islands",
    area: "Greektown / West Loop",
    cuisine: "Greek",
    emoji: "🇬🇷",
    blurb:
      "A Greektown institution since 1971 built for groups — multiple dining rooms, generous plates, and great value just west of downtown.",
    price: "$$",
    website: "https://greekislands.net/",
    mapQuery: "Greek Islands Restaurant 200 S Halsted St Chicago",
  },
  {
    title: "Pequod's Pizza",
    area: "Lincoln Park",
    cuisine: "Deep-dish pizza",
    emoji: "🍕",
    blurb:
      "Famous for its caramelized-cheese crust and a local favorite. Casual, walk-in friendly, and a couple of pies feed the table cheaply.",
    price: "$$",
    website: "https://pequodspizza.com/chicago/",
    mapQuery: "Pequod's Pizza 2207 N Clybourn Ave Chicago",
  },
  {
    title: "The Gage",
    area: "The Loop · Michigan Ave",
    cuisine: "Gastropub",
    emoji: "🍻",
    blurb:
      "A lively gastropub right across from Millennium Park — a slightly nicer night out that still handles groups well. Great for after The Bean.",
    price: "$$–$$$",
    website: "https://thegagechicago.com/",
    mapQuery: "The Gage 24 S Michigan Ave Chicago",
  },
  {
    title: "Tempo Cafe",
    area: "Gold Coast",
    cuisine: "Diner · all-day",
    emoji: "🍳",
    blurb:
      "A beloved Gold Coast diner with a huge menu and budget prices. Casual and walk-in easy — best for an early group dinner (closes 8 PM).",
    price: "$",
    website: "https://tempochicago.com/",
    mapQuery: "Tempo Cafe 6 E Chestnut St Chicago",
  },
];
